### ISSUE TITLE
use `parse_color()` to convert `*_color` in `config.h`

### ISSUE THREAD

**Issue by apprehensions** [kolunmi/dwlb#10]
I've noticed that instead of converting hex to a `pixman_color_t` in the config.h despite there being a function that does convert, it is not being used, is there a way to make it so that at run-time, all the colors `active_fg_color`, `active_bg_color`, etc. get converted to hex and get used?

**Comment by kolunmi** [comment]
Hello! You can convert a hex string color to a `pixman_color_t` by entering corresponding red, green, blue, and alpha values into the struct initializer, i.e. `"#ffeeddff` would become `{ .red = 0xffff, .green = 0xeeee, .blue = 0xdddddd, .alpha = 0xffff, }`. `parse_color` is actually used multiple times in the program, when reading color values from cli options and in status text. Did I understand your question correctly? If not, could you elaborate a bit more on what you need the program to do? Thank you.

**Comment by apprehensions** [comment]
Simply, use hex colors instead of `pixman_color_t` in `config.h`, by using `parse_color` at run-time, but considering this and realizing the program directly forwards to pixman, i guess the better solution would be a macro such as `HEXTOPIXCOL`? i can try to implement that in a pull request, also removing the need for `parse_color` by using the macro.

**Comment by kolunmi** [comment]
The manual conversion from a hex string to a `pixman_color_t` is so simple that I'm not sure if this is necessary, given how inefficient it would be to parse the string at runtime. We would also still need fallback `pixman_color_t` values if the string was invalid. If you are able to produce a macro that can convert the string without `parse_color`, feel free to submit a pull request. Thanks.
