### ISSUE TITLE
Build issue on Musl libc systems

### ISSUE THREAD

**Issue by yveszoundi** [kolunmi/dwlb#2]
### System Information

- OS: Void Linux x86_64 (musl flavor)
- dwlb: Commit [fe2d0e6](https://github.com/kolunmi/dwlb/commit/fe2d0e670f9ddd80a932da6008cbce514bb306e8) 
- wlroots: 0.16.x (standard Void Linux devel package)

### Current behavior

`dwlb` fails to compile with `fd_set` reported as unknown type name.

### Expected behavior

Once build dependencies are satisfied, the code should compile cleanly on `musl` libc systems.

### Relevant logs and/or media

Here is the full compilation failure output.

```
$ rm config.h; make clean; make
rm -f dwlb dwlb.o
cp config.def.h config.h
cc -Wall -Wextra -Wno-unused-parameter -Wno-format-truncation -g -DUTF8PROC_EXPORTS -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1   -c -o dwlb.o dwlb.c
dwlb.c: In function 'event_loop':
dwlb.c:913:17: error: unknown type name 'fd_set'
  913 |                 fd_set rfds;
      |                 ^~~~~~
dwlb.c:914:17: warning: implicit declaration of function 'FD_ZERO'; did you mean 'FP_ZERO'? [-Wimplicit-function-declaration]
  914 |                 FD_ZERO(&rfds);
      |                 ^~~~~~~
      |                 FP_ZERO
dwlb.c:915:17: warning: implicit declaration of function 'FD_SET'; did you mean 'L_SET'? [-Wimplicit-function-declaration]
  915 |                 FD_SET(STDIN_FILENO, &rfds);
      |                 ^~~~~~
      |                 L_SET
dwlb.c:922:21: warning: implicit declaration of function 'select' [-Wimplicit-function-declaration]
  922 |                 if (select(MAX(sock_fd, wl_fd) + 1, &rfds, NULL, NULL, NULL) == -1)
      |                     ^~~~~~
dwlb.c:925:21: warning: implicit declaration of function 'FD_ISSET' [-Wimplicit-function-declaration]
  925 |                 if (FD_ISSET(STDIN_FILENO, &rfds))
      |                     ^~~~~~~~
make: *** [<builtin>: dwlb.o] Error 1
```

### Other comment

I don't know if it's the best way to address this, but adding the line below in `dwlb.c` fixes the issue for me:
```#include <sys/select.h>```

**Comment by podit** [comment]
`#include <sys/select.h>` has been added in a refactor currently being staged for a merge into main. presumably [d25242c](https://github.com/kolunmi/dwlb/commit/d25242c29949a209b5063e64f8ecd35b153fa260) fixes this?

**Comment by yveszoundi** [comment]
That pending change fixes compilation errors for me, thanks.

**Comment by kolunmi** [comment]
Thanks for bringing this to my attention. It has been fixed.
