### ISSUE TITLE
dwlb & someblocks start

### ISSUE THREAD

**Issue by kristoferus75** [kolunmi/dwlb#22]
Hi !

if i start with dwl with

`dwl -s 'autostart_dwl.sh' 2>&1 | tee "$LOGDIR"/dwl.log `

autostart_dwl.sh:
```

dwlb -ipc 
someblocks -p | dwlb -status-stdin all & 
```

i cannot see someblocks

but if i start in terminal in dwl

`someblocks -p | dwlb -status-stdin all & `

i see someblocks and it works

Who can start someblocks with dwlb so that i dont need manualy start it in an terminal ?

thanks

**Comment by kolunmi** [comment]
Hello! The shell is waiting for `dwlb -ipc` to exit, so as long as dwlb is running, someblocks will never execute. Try something like:
```sh
dwlb -ipc &
sleep 0.1
someblocks -p | dwlb -status-stdin all
```

**Comment by kristoferus75** [comment]
thanks it works :-)
