### ISSUE TITLE
Tags without focus are highlighted in blue

### ISSUE THREAD

**Issue by wesbluemarine** [kolunmi/dwlb#23]
Is this behavior intentional?

**Comment by kolunmi** [comment]
Hello! It's been a while, but I think you can solve your issue by passing `-occupied-fg-color` and `-occupied-bg-color` with values to match `inactive-fg-color` and `inactive-bg-color`. Hope this helps!

**Comment by wesbluemarine** [comment]
It works as expected! Thanks!
