### ISSUE TITLE
Nerdfont rendering issue

### ISSUE THREAD

**Issue by DhruvaSambrani** [kolunmi/dwlb#31]
![Unsaved Image 1](https://github.com/kolunmi/dwlb/assets/44899822/db331dd1-2831-4c3d-bedb-e0485df27320)

Spacing is messed up

**Comment by kolunmi** [comment]
I'm not quite sure what the issue is here. The width of the box is based on the width of the characters as reported by fcft. Does it only occur with the spotify glyph?

**Comment by DhruvaSambrani** [comment]
No, all the icons are smushed together. The rendering is marginally better if I add a space after the icon, but it is still not accurate

**Comment by DhruvaSambrani** [comment]
Looks like it was a font issue and not a rendering issue
