### ISSUE TITLE
Include real world status command examples

### ISSUE THREAD

**Issue by josephreynolds1** [kolunmi/dwlb#4]
Please include some real world status command examples.  Documentation of command is confusing.

Also is it possible to use applications like someblocks to populate status data?

**Comment by kolunmi** [comment]
Hello! I added an example to README.md. Does it clarify the usage?

You could use someblocks to populate status data like this:
```bash
someblocks -p | while read -r line; do dwlb -status all "$line"; done
```
Or you could do some slight modifications to someblocks to make it write to dwlb's socket.

**Comment by gozenka** [comment]
Adding that command to the README could help a lot.
I struggled, overcomplicating stuff via mkfifo before realizing I could do exactly that one-liner.

**Comment by kolunmi** [comment]
Added
