### ISSUE TITLE
[Feature Request] Option to use Title area for custom text via stdin

### ISSUE THREAD

**Issue by gozenka** [kolunmi/dwlb#5]
Similar to `-status`, an option such as `-title` can be offered to display anything in the title area, rather than window title. Or a delimiter can be used to separate the text supplied from stdin into the two areas.

This would be useful for displaying things like current music playing or time / date or any custom information in the middle, while displaying other status information on the right.

For such cases, it would also make sense to allow centering the text in the title area, instead of aligning it to the left.

**Comment by kolunmi** [comment]
Added in b1e0f99. Let me know if there are any issues

**Comment by gozenka** [comment]
It works fine. Thank you!
