### ISSUE TITLE
Possible support for the official IPC patch

### ISSUE THREAD

**Issue by 0x72756279** [kolunmi/dwlb#6]
This is by far the best option I found for a bar.

dwl now have an "official" [patch](https://github.com/djpohly/dwl/wiki/ipc) for IPC in it's wiki.

Any way to adapt support for using this patch as well?

**Comment by idr4n** [comment]
I second this. I have patched DWL with the official IPC patch and it doesn't work with dwlb yet unfortunately. Otherwise, thanks for a really nice bar!
